//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TazeDirektWpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<int> TedarikciId { get; set; }
        public Nullable<bool> AnalizliMi { get; set; }
        public Nullable<bool> OrganikMi { get; set; }
        public Nullable<bool> YerliUretimMi { get; set; }
        public Nullable<bool> SekersizMi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string ResimYolu { get; set; }
        public Nullable<int> KategoriId { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
    }
}
